security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        users_in_db:
            entity:
                class: App\Entity\User
                property: username
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_db

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /
                username_parameter: _username
                password_parameter: _password

            logout:
                path: app_logout
                target: /

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/contact, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/realisations, roles: PUBLIC_ACCESS }
